### ISSUE TITLE
Missing R scripts used in m_NASIS_100m.R

### ISSUE THREAD

**Issue by SongchaoChen** [aramcharan/US_SoilGrids100m#1]
Amanda and Tom, many thanks for sharing your work in the high-resolution map and I learned a lot from it. However, I found two R scripts (`saveRDS_funtions.R` and `wrapper.predict_cs.R`) mentioned in `m_NASIS_100m.R `were missing. Could you upload them? Thanks in advance.
Best wishes,
Songchao

**Comment by aramcharan** [comment]
Hi Songchao,

thank you for your interest in our work. The scripts you are looking for can be found in the links below:
https://github.com/ISRICWorldSoil/SoilGrids250m/blob/master/grids/models/saveRDS_functions.R
https://github.com/ISRICWorldSoil/SoilGrids250m/blob/master/grids/models/wrapper.predict_cs.R

The simplest thing would be to clone the SoilGrids250m repository.
