### ISSUE TITLE
Projection information?

### ISSUE THREAD

**Issue by swood-ecology** [aramcharan/US_SoilGrids100m#2]
I can't find any information on the projection of this product. I suspect it's different from the global 250m product because when I use `raster::extract()` in R, it automatically converts the CRS of my points data frame for the 100m US product, but not the 250m global product.

**Comment by thengl** [comment]
All maps in this project were aligned to the USGS National Map (https://nationalmap.gov/small_scale/atlasftp.html) grid with Albers Equal Area projection. You can get the grid definition of each layer by running GDALinfo of course e.g.:

```
> raster("/mnt/nas/USA48/elev48i0100a.tif")                                   
class       : RasterLayer 
dimensions  : 31390, 49810, 1563535900  (nrow, ncol, ncell)
resolution  : 100, 100  (x, y)
extent      : -2540000, 2441000, 119000, 3258000  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0 
data source : /mnt/nas/USA48/elev48i0100a.tif 
names       : elev48i0100a 
values      : -86, 4402  (min, max)
attributes  :
         ID  OID Value Count
 from:    0    0   -86    34
 to  : 4455 4455  4402     1
```
