### ISSUE TITLE
Scale of pH maps?

### ISSUE THREAD

**Issue by kanedan29** [aramcharan/US_SoilGrids100m#3]
I've been working with the pH maps and am wondering about the scale. Values are in the range of ~40-80. As best I can tell the numbers are actually pH*10 (i.e. actual pH is 4-8, which would be typical for soils). Is that correct? Thanks!

**Comment by aramcharan** [comment]
Correct. This was done to reduce the file size (integers have lower storage requirements than floats).

**Comment by kanedan29** [comment]
Thanks!
