### ISSUE TITLE
Scale of SOC layers?

### ISSUE THREAD

**Issue by kanedan29** [aramcharan/US_SoilGrids100m#4]
Similar to my previous [question](https://github.com/aramcharan/US_SoilGrids100m/issues/3) re: scale of pH layers, are % SOC layers also multiplied by 10 so they can be stored as integers? Are they on a g C per kg soil equivalent? Thanks!

**Comment by thengl** [comment]
Yes they are in permiles. See:
https://github.com/aramcharan/US_SoilGrids100m/blob/master/Soil_Property_and_Class_Models_Codes/META_GEOTIFF_USA48.csv

**Comment by kanedan29** [comment]
Thank you!
